"""Tests for the context transformer."""

from __future__ import annotations

import json
import unittest
from pathlib import Path

import transform

ROOT = Path(__file__).resolve().parent


class TransformTests(unittest.TestCase):
    """Verify that transform.py generates correct outputs from context + templates."""

    def test_build_outputs_renders_expected_files(self) -> None:
        rendered = transform.build_outputs(ROOT)
        expected_paths = [
            "AGENTS.md",
            "CLAUDE.md",
            ".github/copilot-instructions.md",
            ".github/instructions/backend.instructions.md",
            ".github/instructions/frontend.instructions.md",
            ".github/instructions/tests.instructions.md",
            ".github/instructions/api.instructions.md",
            ".claude/rules/backend.md",
            ".claude/rules/frontend.md",
            ".claude/rules/tests.md",
            ".claude/rules/api.md",
            ".github/agents/reviewer.agent.md",
            ".github/skills/loan-workbench-delivery/SKILL.md",
            ".github/prompts/implement-loan-workbench-change.prompt.md",
            ".github/hooks/context-guard.json",
        ]
        for path in expected_paths:
            self.assertIn(path, rendered, f"Missing output: {path}")

    def test_agents_contains_app_identity(self) -> None:
        rendered = transform.build_outputs(ROOT)
        self.assertIn("Loan Workbench", rendered["AGENTS.md"])
        self.assertIn("Express 4", rendered["AGENTS.md"])

    def test_claude_bridge_imports_agents(self) -> None:
        rendered = transform.build_outputs(ROOT)
        self.assertIn("@AGENTS.md", rendered["CLAUDE.md"])

    def test_copilot_bridge_matches_agents_content(self) -> None:
        rendered = transform.build_outputs(ROOT)
        self.assertIn("Loan Workbench", rendered[".github/copilot-instructions.md"])

    def test_same_context_in_copilot_and_claude_scoped_rules(self) -> None:
        rendered = transform.build_outputs(ROOT)
        copilot = rendered[".github/instructions/backend.instructions.md"]
        claude = rendered[".claude/rules/backend.md"]
        self.assertIn("Backend Application Contract", copilot)
        self.assertIn("Backend Application Contract", claude)
        self.assertIn("Middleware Order", copilot)
        self.assertIn("Middleware Order", claude)

    def test_copilot_scope_frontmatter(self) -> None:
        rendered = transform.build_outputs(ROOT)
        self.assertIn(
            'applyTo: "src/backend/src/**"',
            rendered[".github/instructions/backend.instructions.md"],
        )
        self.assertIn(
            'applyTo: "src/frontend/src/**"',
            rendered[".github/instructions/frontend.instructions.md"],
        )
        self.assertIn(
            'applyTo: "src/backend/tests/**"',
            rendered[".github/instructions/tests.instructions.md"],
        )

    def test_claude_scope_frontmatter(self) -> None:
        rendered = transform.build_outputs(ROOT)
        self.assertIn(
            '"src/backend/src/**/*.ts"',
            rendered[".claude/rules/backend.md"],
        )
        self.assertIn(
            '"src/frontend/src/**/*.ts"',
            rendered[".claude/rules/frontend.md"],
        )

    def test_skill_has_frontmatter_and_content(self) -> None:
        rendered = transform.build_outputs(ROOT)
        skill = rendered[".github/skills/loan-workbench-delivery/SKILL.md"]
        self.assertIn("name: loan-workbench-delivery", skill)
        self.assertIn("Delivery Workflow", skill)

    def test_prompt_has_frontmatter_and_content(self) -> None:
        rendered = transform.build_outputs(ROOT)
        prompt = rendered[".github/prompts/implement-loan-workbench-change.prompt.md"]
        self.assertIn("agent: Plan", prompt)
        self.assertIn("Change Planning", prompt)

    def test_hook_is_valid_json(self) -> None:
        rendered = transform.build_outputs(ROOT)
        hook = json.loads(rendered[".github/hooks/context-guard.json"])
        self.assertEqual(hook["hookName"], "loan-workbench-context-guard")

    def test_all_markdown_outputs_have_notice(self) -> None:
        rendered = transform.build_outputs(ROOT)
        for path, content in rendered.items():
            if path.endswith(".json"):
                continue
            self.assertIn(
                "Auto-generated by transform.py",
                content,
                f"Missing generated notice in {path}",
            )

    def test_templates_contain_no_app_context(self) -> None:
        """Templates must be pure format shells with no application content."""
        templates_dir = ROOT / ".code.agent" / "templates"
        app_terms = ["Loan Workbench", "Express", "Vitest", "better-sqlite3"]
        for tpl_file in templates_dir.glob("*.tpl"):
            text = tpl_file.read_text(encoding="utf-8")
            for term in app_terms:
                self.assertNotIn(
                    term,
                    text,
                    f"Template {tpl_file.name} contains app context '{term}'",
                )


if __name__ == "__main__":
    unittest.main()