"""Generate coding-agent context files from .code.agent/ sources.

Reads reusable context from .code.agent/context/*.md and applies pure format
templates from .code.agent/templates/*.tpl to produce outputs for GitHub
Copilot, Claude Code, and Codex.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path


TOKEN_PATTERN = re.compile(r"\{\{([A-Z_]+)\}\}")


def read_text(path: Path) -> str:
    """Read a UTF-8 text file and normalize its trailing newline."""
    return path.read_text(encoding="utf-8").rstrip() + "\n"


def load_graph(root: Path) -> dict:
    """Load the graph configuration from .code.agent/graph.json."""
    return json.loads(read_text(root / ".code.agent" / "graph.json"))


def resolve_content(root: Path, graph: dict, content_keys: list[str]) -> str:
    """Concatenate context files referenced by an output entry."""
    context_map = graph["context"]
    parts = []
    for key in content_keys:
        path = root / context_map[key]
        parts.append(read_text(path).rstrip())
    return "\n\n".join(parts)


def build_notice(output_path: str) -> str:
    """Build a generated-file notice for the given output path."""
    return (
        f"Auto-generated by transform.py for {output_path}. "
        "Edit .code.agent/context/ sources, then rerun transform.py."
    )


def render_template(template_text: str, replacements: dict[str, str]) -> str:
    """Replace all placeholder tokens in a template with resolved values."""
    rendered = template_text
    for name, value in replacements.items():
        rendered = rendered.replace(f"{{{{{name}}}}}", value)
    missing = sorted(set(TOKEN_PATTERN.findall(rendered)))
    if missing:
        raise ValueError(f"Unresolved tokens: {', '.join(missing)}")
    return rendered.rstrip() + "\n"


def render_output(root: Path, graph: dict, output: dict) -> str:
    """Render a single output file from its template and context sources."""
    template_path = root / graph["templates"][output["template"]]
    template_text = read_text(template_path)

    replacements: dict[str, str] = {
        "GENERATED_NOTICE": build_notice(output["path"]),
    }

    content_keys = output.get("content", [])
    if content_keys:
        replacements["CONTENT"] = resolve_content(root, graph, content_keys)

    for var_name, var_value in output.get("vars", {}).items():
        replacements[var_name] = var_value

    return render_template(template_text, replacements)


def build_outputs(root: Path) -> dict[str, str]:
    """Render all configured outputs into an in-memory mapping."""
    graph = load_graph(root)
    return {o["path"]: render_output(root, graph, o) for o in graph["outputs"]}


def write_outputs(root: Path) -> list[str]:
    """Render all outputs and write them to disk."""
    rendered = build_outputs(root)
    written: list[str] = []
    for path, content in rendered.items():
        target = root / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        written.append(path)
    return written


def check_outputs(root: Path) -> list[str]:
    """Return the list of generated outputs that are missing or out of date."""
    rendered = build_outputs(root)
    stale: list[str] = []
    for path, expected in rendered.items():
        target = root / path
        current = target.read_text(encoding="utf-8") if target.exists() else None
        if current != expected:
            stale.append(path)
    return stale


def main(argv: list[str] | None = None) -> int:
    """Parse arguments and either write or verify generated outputs."""
    args = argv or sys.argv[1:]
    root = Path(__file__).resolve().parent

    if len(args) != 1 or args[0] not in ("--write", "--check"):
        print("Usage: python transform.py --write | --check")
        return 1

    if args[0] == "--write":
        written = write_outputs(root)
        print("Wrote generated files:")
        for p in written:
            print(f"  {p}")
        return 0

    stale = check_outputs(root)
    if stale:
        print("Out of date:")
        for p in stale:
            print(f"  {p}")
        return 1

    print("All generated files are up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())