[mypy]
python_version = 3.11
mypy_path =
	lessons/_common/src,
	lessons/08-microsoft-agent-framework/src,
	lessons/09-google-adk/src,
	lessons/10-langgraph/src,
	lessons/11-crewai/src,
	lessons/12-openai-agents-sdk/src,
	lessons/13-claude-agent-sdk/src,
	lessons/14-multi-agent-deep-dive/agents/src
warn_unused_ignores = True
pretty = True
ignore_missing_imports = True

[mypy-google.*]
ignore_missing_imports = True

[mypy-crewai.*]
ignore_missing_imports = True

[mypy-agents.*]
ignore_missing_imports = True
